---
- name: Install and configure nginx and manage firewall ports
  hosts: "{{ target_hosts }}"
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - role: nginx_setup
    - role: firewall_management