---
- name: Ensure firewalld is installed
  yum:
    name: firewalld
    state: present

- name: Ensure firewalld is running and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open required ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - "22/tcp"
    - "80/tcp"
    - "443/tcp"